name: Build and Push Docker image (Frontend)

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CodeQL Frontend"]
    types:
      - completed
    branches: [main]

jobs:
  docker:
    # Modified condition to be more permissive and explicit
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ajout d'une étape pour les tests unitaires
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint

      - name: Set lowercase owner
        id: vars
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.prod -t ghcr.io/${{ env.OWNER_LC }}/frontend:latest -t ghcr.io/${{ env.OWNER_LC }}/frontend:${{ env.SHORT_SHA }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.OWNER_LC }}/frontend:latest
          docker push ghcr.io/${{ env.OWNER_LC }}/frontend:${{ env.SHORT_SHA }}
