name: Build and Push Docker image (Frontend)

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f Dockerfile.prod -t ghcr.io/${{ github.repository_owner,, }}/frontend:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner,, }}/frontend:latest
